spring:
  data:
    mongodb:
      host: 192.168.3.168
      port: 27017
      username: root
      password: root
      # 指定操作的数据库
      database: file_server

  # consul配置
  cloud:
    consul:
      discovery:
        enabled: false
