apiVersion: autoscaling/v2beta1 
kind: HorizontalPodAutoscaler 
metadata: 
  name: nari-oauth2-server-hpa
  namespace: omsiii
spec: 
  scaleTargetRef: 
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: nari-oauth2-server
  minReplicas: 1 
  maxReplicas: 3 
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 90
#  - type: Pods
#    pods:
#      metricName: packets-per-second
#      targetAverageValue: 1k
#  - type: Object
#    object:
#      metricName: requests-per-second
#     target:
#        apiVersion: extensions/v1beta1
#        kind: Ingress
#        name: main-route
#      targetValue: 10k
