application:
  version: 1.1.0-SNAPSHOT
server:
  port: 8093
  servlet:
    context-path: /oauth2-server

# 配置服务发现
eureka:
  client:
    instanceInfoReplicationIntervalSeconds: 10
    enabled: false
    serviceUrl:
      defaultZone: http://10.100.1.19:8761/eureka/
  instance:
    preferIpAddress: false

spring:
  datasource:
    # oauth2的数据源配置
    oauth2:
      type: com.zaxxer.hikari.HikariDataSource
      jdbc-url: jdbc:mysql://127.0.0.1:3306/boot_in_action?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root
      driverClassName: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 10
        minimum-idle: 10
  redis:
    host: 127.0.0.1
    port: 6379
    database: 2
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 1ms
        min-idle: 0
      shutdown-timeout: 100ms
  security:
    user:
      name: admin
      password: admin

# logback配置文件路径
logging:
  config: classpath:logback.xml

