application:
  version: 1.0-SNAPSHOT
server:
  port: 8093
  servlet:
    context-path: /
  # 以下是undertow内嵌服务器的配置项
  undertow:
    buffer-size: 1024
    direct-buffers: true
    eager-filter-init: true
    io-threads: 8
    worker-threads: 128
    max-http-post-size: -1B

# actuator相关配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      enabled: true
      show-details: always
  health:
    redis:
      enabled: false

# 配置服务发现
eureka:
  client:
    instanceInfoReplicationIntervalSeconds: 10
    enabled: true
    serviceUrl:
      defaultZone: http://10.100.1.19:8761/eureka/
  instance:
    preferIpAddress: false

spring:
  application:
    name: NARI-OAUTH2-SERVER
  output:
    ansi:
      enabled: always
  datasource:
    # metabase的数据源配置
    metabase:
      type: com.zaxxer.hikari.HikariDataSource
      jdbc-url: jdbc:oracle:thin:@10.100.1.20:1521:dicp
      username: metabase
      password: metabase
      driverClassName: oracle.jdbc.driver.OracleDriver
      hikari:
        maximum-pool-size: 10
        minimum-idle: 10
    # pi6000的数据源，用于读取用户信息
    pi6000:
      type: com.zaxxer.hikari.HikariDataSource
      jdbc-url: jdbc:oracle:thin:@10.100.1.20:1521:dicp
      username: oms_pi6000
      password: oms_pi6000
      driverClassName: oracle.jdbc.driver.OracleDriver
      hikari:
        maximum-pool-size: 8
        minimum-idle: 2
  jackson:
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+08:00
  redis:
    host: 10.100.1.19
    port: 6379
    database: 2
#    password:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 1ms
        min-idle: 0
      shutdown-timeout: 100ms
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  security:
    user:
      name: admin
      password: oms_admin

# logback配置文件路径
logging:
#  config: file:${OAUTH2_CONFIG_PATH}/logback.xml
  config: classpath:logback.xml

